export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const RESET_STORE = 'RESET_STORE';

export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";

export const ALL_SAMPLE_PROPOSALS = "ALL_SAMPLE_PROPOSALS";
export const ALL_SAMPLE_PROPOSALS_FAILURE = "ALL_SAMPLE_PROPOSALS_FAILURE";

export const PROPOSAL_QUESTION = "PROPOSAL_QUESTION";
export const PROPOSAL_QUESTION_FAILURE = "PROPOSAL_QUESTION_FAILURE";

export const ALL_CHATS = "ALL_CHATS";
export const ALL_CHATS_FAILURE = "ALL_CHATS_FAILURE";

export const ALL_MESSAGE_FOR_CHAT = "ALL_MESSAGE_FOR_CHAT";
export const ALL_MESSAGE_FOR_CHAT_FAILURE = "ALL_MESSAGE_FOR_CHAT_FAILURE";

export const REFERSH_TOKEN = "REFERSH_TOKEN";
export const REFERSH_TOKEN_FAILURE = "REFERSH_TOKEN_FAILURE";

export const GENERATE_PROPOSAL = "GENERATE_PROPOSAL";
export const GENERATE_PROPOSAL_FAILURE = "GENERATE_PROPOSAL_FAILURE";
