// import { Inter } from "next/font/google";
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }



"use client";
import { Inter } from "next/font/google";
import "./globals.css";

import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react";
import { store, persistor } from "./store/store";
import ToastProvider from "@/components/common/ToastProvider";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <Provider store={store}>
            <PersistGate loading={null} persistor={persistor}>
              <ToastProvider>
                {children}
              </ToastProvider>
            </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
